# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

configfile: "config/config.yaml"

localrules: all, report, clean

rule all:
    message: "Run entire analysis and compile report."
    input:
        "report/report.pdf",


rule report:
    message: "Compile report."
    params:
        fn="report"
    input:
        tex="report/report.tex",
        bib="report/references.bib"
    output: "report/report.pdf"
    shell:
        """
        pdflatex -output-directory report {input.tex}
        cd report; bibtex {params.fn}; cd ..
        pdflatex -output-directory report {input.tex}
        pdflatex -output-directory report {input.tex}
        """


rule dag:
     message: "Plot dependency graph of the workflow."
     output:
         dot="resources/dag.dot",
         pdf="resources/dag.pdf"
     shell:
         """
         snakemake --rulegraph > {output.dot}
         dot -Tpdf -o {output.pdf} {output.dot}
         """


rule clean:
    message: "Remove all build results but keep downloaded data."
    run:
         import shutil
         import os

         shutil.rmtree("resources",ignore_errors=True)
         shutil.rmtree("results",ignore_errors=True)
         fn = "report/report.pdf"
         os.remove(fn) if os.path.exists(fn) else None
         print("Data downloaded to data/ has not been cleaned.")

        
rule sync:
    params:
        cluster=config["cluster"],
    shell:
        """
        rsync -uvarh --no-g --exclude-from=.syncignore-send . {params.cluster}
        rsync -uvarh --no-g --exclude-from=.syncignore-receive {params.cluster} .
        """
